version: '3.8'
services:
   my-pytorch-app:
      build: .
      volumes:
         - ./app:/usr/src/app
         - ./input:/usr/src/input
         - ./output:/usr/src/output
      command: python main.py
